site_name: Jigar Vyas
site_url: https://jigardvyas.github.io/jigarvyas/
repo_url: https://github.com/jigardvyas/jigarvyas
theme: readthedocs
nav:
    - Home:
        - "Home": "Index/index.md"
    - Profile:
          - "About Me": "Profile/aboutMe.md"
          - "Resume": "Profile/resume.md"
          - "Contact Me": "Profile/contactMe.md"