site_name: Jigar Vyas
site_url: https://jigardvyas.github.io/jigarvyas/
repo_url: https://github.com/jigardvyas/jigarvyas
theme: readthedocs
nav:
    - Home: index.md
    - Resume: resume.md
    - Contact Me: contact_me.md